### PR TITLE
KET 370 remove modules from duo_starter

### PR DESCRIPTION
**Pull request by Matt-Hood**
**Steps taken:**
- Removed all Drupal modules from duo_starter
- Adding support for these modules to the sites still using them in their local composer.json file (Kettering and Bracewell) 

**Test instructions:**
- Verify all drupal modules are removed

**Next steps:**
- create new release tag in duo_starter (9.0.2 i think is next in line)
- Add support for these removed modules for Bracewell and Kettering
- Pull duo_starter:9.0.2 into ketteringd8 composer
- Pull duo_starter:9.0.2 into bracewelld8 composer

**Jira ticket:**
[KET-370](https://codeandtheory.atlassian.net/secure/RapidBoard.jspa?rapidView=967&projectKey=KET&modal=detail&selectedIssue=KET-370)

### CODE REVIEW

**Comment by damienmckenna** [comment]
I think this is the wrong way to accomplish the goal, I think you should remove duo_starter from the projects.

**Comment by Matt-Hood** [comment]
@damienmckenna Agreed, removing duo_starter from the projects is our end goal but I believe there are some blockers there. @joshuaboltz @richlawson Is this possible sooner rather than later?

**Comment by damienmckenna** [comment]
I just think that removing these modules from the distro will break it for other codebases.

**Comment by Matt-Hood** [comment]
I confirmed with Rich beforehand that the only two codebases actively using duo_starter are Bracewell and Kettering. I have tickets currently on both projects to handle these changes.

**Comment by damienmckenna** [comment]
Ok, but I would still go back to the original point of decoupling the codebases from duo_starter so that they can stand on their own.

**Comment by Matt-Hood** [comment]
I will look into if that is feasible and get back to you, thanks Damien!

**Review by joshuaboltzmc — APPROVED** [review]

**Comment by damienmckenna** [comment]
> I confirmed with Rich beforehand that the only two codebases actively using duo_starter are Bracewell and Kettering. I have tickets currently on both projects to handle these changes.

Given that this is a public repository, are we sure that there aren't other sites using it?

**Pull request closed without merging**
